

name: integration

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t ezeidn/ezedin_code
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
      - run: docker push ezeidn/ezedin_code
